server:
  port: 8100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2 #duas request por 10s
        limit-refresh-period: 10s
  bulkhead:
    instances:
      default:
       max-concurrent-calls: 10 #execuções simultâneas
  retry:
    instances:
      default:
        max-attempts: 5
      bug-test:
        max-attempts: 5 #quantidade de request antes do erro
        wait-duration: 1s #quantos segundos vai demorar fazer cada request
        enable-exponential-backoff: true #segundos em exponencial, demora mais tempo
      
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
  flyway:
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    user: root
    password: root
   
  sleuth: #loggar a aplicação    sampler:      probability: 1.0 #0.25 produção
   
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  show-actuator: true
