server:
  port: 8100
  
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true 
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: root
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
